// Website Configuration Constants
export const CONFIG_GROUPS = {
  GENERAL: 'GENERAL',
  CONTACT: 'CONTACT',
  SOCIAL: 'SOCIAL',
  MENU: 'MENU',
} as const;

export type ConfigGroup = keyof typeof CONFIG_GROUPS;

export const CONFIG_KEYS = {
  // GENERAL
  WEBSITE_NAME: 'WEBSITE_NAME',
  WEBSITE_SLOGAN: 'WEBSITE_SLOGAN',
  WEBSITE_LOGO: 'WEBSITE_LOGO',
  WEBSITE_FAVICON: 'WEBSITE_FAVICON',
  
  // CONTACT
  CONTACT_HOTLINE: 'CONTACT_HOTLINE',
  CONTACT_EMAIL: 'CONTACT_EMAIL',
  CONTACT_ADDRESS: 'CONTACT_ADDRESS',
  CONTACT_MAP_IFRAME: 'CONTACT_MAP_IFRAME',
  
  // SOCIAL
  SOCIAL_FACEBOOK: 'SOCIAL_FACEBOOK',
  SOCIAL_ZALO: 'SOCIAL_ZALO',
  SOCIAL_YOUTUBE: 'SOCIAL_YOUTUBE',

  // MENU
  MENU_HOME: 'MENU_HOME',
  MENU_ABOUT: 'MENU_ABOUT',
  MENU_SERVICES: 'MENU_SERVICES',
  MENU_PROJECTS: 'MENU_PROJECTS',
  MENU_NEWS: 'MENU_NEWS',
  MENU_CONTACT: 'MENU_CONTACT',
} as const;
