// Website Configuration Constants
export const CONFIG_GROUPS = {
  GENERAL: 'GENERAL',
  CONTACT: 'CONTACT',
  SOCIAL: 'SOCIAL',
  MENU: 'MENU',
  STATISTICS: 'STATISTICS',
} as const;

export type ConfigGroup = keyof typeof CONFIG_GROUPS;

export const CONFIG_KEYS = {
  // GENERAL
  WEBSITE_NAME: 'WEBSITE_NAME',
  WEBSITE_FULLNAME: 'WEBSITE_FULLNAME',
  WEBSITE_SLOGAN: 'WEBSITE_SLOGAN',
  WEBSITE_LOGO: 'WEBSITE_LOGO',
  WEBSITE_FAVICON: 'WEBSITE_FAVICON',
  
  // CONTACT
  CONTACT_HOTLINE: 'CONTACT_HOTLINE',
  CONTACT_EMAIL: 'CONTACT_EMAIL',
  CONTACT_ADDRESS: 'CONTACT_ADDRESS',
  CONTACT_MAP_IFRAME: 'CONTACT_MAP_IFRAME',
  
  // SOCIAL
  SOCIAL_FACEBOOK: 'SOCIAL_FACEBOOK',
  SOCIAL_ZALO: 'SOCIAL_ZALO',
  SOCIAL_YOUTUBE: 'SOCIAL_YOUTUBE',

  // MENU
  MENU_HOME: 'MENU_HOME',
  MENU_ABOUT: 'MENU_ABOUT',
  MENU_EVENTS: 'MENU_EVENTS',
  MENU_SOUND_LIGHT: 'MENU_SOUND_LIGHT',
  MENU_RENTAL: 'MENU_RENTAL',
  MENU_NEWS: 'MENU_NEWS',
  MENU_CONTACT: 'MENU_CONTACT',

  // STATISTICS
  STATS_FIELDS: 'STATS_FIELDS',
  STATS_EVENTS: 'STATS_EVENTS',
  STATS_BRANDS: 'STATS_BRANDS',
} as const;
